name: corinthians
version: "1.0.0"
profile: corinthians

models:
  corinthians:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
    auditoria:
      +materialized: table
      +schema: auditoria

seeds:
  corinthians:
    +schema: staging
